- sql/pg_net--0.1.sql
- src/worker.c
- test/expected/test_http_get.out
- test/sql/test_http_get.sql
Fixes #4. When doing invalid requests:
```sql
-- invalid protocol
select net.http_get('net://supabase.io');
-- invalid host name
select net.http_get('http://new.ycombinator.com');
```
We now get:
```sql
select id, url, error_msg from net.http_request_queue;
┌────┬────────────────────────────┬────────────────────────────┐
│ id │            url             │         error_msg          │
├────┼────────────────────────────┼────────────────────────────┤
│  1 │ net://supabase.io          │ Unsupported protocol       │
│  2 │ http://new.ycombinator.com │ Couldn't resolve host name │
└────┴────────────────────────────┴────────────────────────────┘
```
Additionally, also handles cases where there's no body and content-type:
```sql
select net.http_get('http://wikipedia.org');
select id, …
```
> Handle requests errors and responses with empty body and content-type

- sql/pg_net--0.1.sql
- test/expected/test_http_collect_response.out
- test/expected/test_http_get.out
- test/sql/test_http_collect_response.sql
- test/sql/test_http_get.sql
Remove async parameter from `http_get` and default to always async
The background worker is not able to see uncommitted requests in the `net.http_request_queue` which means creating a request and retrieving the result needs to happen in separate transactions. That is a reasonable hurdle for the async interface but it prevent a sync interface being implemented in terms of the async interface in the sql layer because the work is never visible to the background worker & `_await_response` will hang forever.
resolves #18
> remove async param from http_get

- sql/pg_net--0.1.sql
- src/worker.c
Feature
Support POST requests via `net.http_post()`. Right now the function is mostly copypasting from `http_get()`, but I think in the future this should be refactored to use a (public?) generic function `net.http()`.
@olirice the order of arguments to `net.http_post()` is a bit out of place since required arguments have to be listed first - let me know if you want them changed. Also I see I'm failing the pytest stuff - anything I should look at? Do you want me to add a test as well? (haven't looked at how it's setup)
@steve-chavez CMIIW, we currently ignore `params` and `headers` in the request right? Atm `content_type` is handled separately, but I think we should handle it together with `headers`. In retrospect, I probably should've omitted `content_type` in the SQL too... (was …
> feat: support POST

- sql/pg_net--0.1.sql
- src/worker.c
https://curl.se/libcurl/c/libcurl-url.html
also change append query code with curl.
leaving `_urlencode` in to keep the tests passing
also granted everything to (hardcoded) `postgres` - probably not correct but we'll cross that bridge when we come to it
> feat: support params directly in url

- docs/api.md
- sql/pg_net--0.1.sql
- src/worker.c
- test/fixtures.sql
- test/test_http_requests_deleted_after_ttl.py
TTL is `3 days` by default, but can be configured with:
```sql
alter system set pg_net.ttl TO '5 minutes';
select pg_reload_conf();
show pg_net.ttl;
-- 5 minutes
```
> Adds TTL in worker

- sql/pg_net--0.1.sql
- test/test_http_post_collect.py
A valid json object that includes a double quote escaped within a string causes an error.
Not sure if this is the best way to fix this!
```
postgres=# select json_build_object('foo', 'b"ar')::text;
json_build_object
-------------------
{"foo" : "b\"ar"}
(1 row)
postgres=# select json_build_object('foo', 'b"ar')::text::bytea;
ERROR:  invalid input syntax for type bytea
postgres=# select convert_to(json_build_object('foo', 'b"ar')::text, 'UTF8');
convert_to
--------------------------------------
\x7b22666f6f22203a2022625c226172227d
(1 row)
```
> fix: allow usage of double quotes within json bodies

- .gitignore
- docs/contributing.md
- nix/deploy.nix
- nix/nginx/conf/nginx.conf
- nix/nginx/conf/slow-reply.conf
- nix/nginx/logs/error.log
- nix/pgScript.nix
- shell.nix
- src/worker.c
- test/test_http_timeout.py
Closes #36.
Also helps with https://github.com/supabase/pg_net/issues/13, since a request will only block other requests from completing for 1 second(the default timeout).
> Add timeout

- .clang-format
- Makefile
- nix/pg_net.nix
- sql/pg_net--0.2--0.3.sql
- sql/pg_net.sql
- src/util.c
- src/worker.c
- test/conftest.py
- test/test_http_get_collect.py
- test/test_http_post_collect.py
- test/test_http_requests_deleted_after_ttl.py
- test/test_http_timeout.py
Fixes #46, #13.
This PR integrates the [libuv](https://github.com/libuv/libuv) event loop with `curl_multi_socket_action` to replace the `curl_multi_perform`-based approach. Incremental changes wasn't really possible, so this is practically a half-rewrite (sorry about the mess!)
The main changes are:
- Use libuv as the event loop. Previously we also have a loop which mostly dealth with TTL and submitting new requests to curl. We integrate these logic into an [idle handle](https://docs.libuv.org/en/latest/guide/utilities.html#idler-pattern) - basically these let you run something once per loop iteration.
- Unlike the previous `curl_multi_perform` implementation, we now submit requests to curl one by one, each in its own transaction. This fixes #13 and sidesteps the need for the …
> feat: libuv

- docs/api.md
- sql/pg_net--0.3--0.4.sql
Bug fix
other db roles are unable to use the api
other db roles are able to invoke the api functions
Related: https://github.com/supabase/supabase/issues/4883
> fix: alter api functions to be security definer ones

- README.md
- docs/api.md
Docs Update
The [API documentation](https://github.com/supabase/pg_net/blob/master/docs/api.md) does not include net.http_delete. Also each request function signature still contains a warning against the usage of timeout parameters, even though the bug that necessitated the warning had been resolved. 
Please link any relevant issues here.
- I removed the timeout warning comments from the request functions. 
- I added the net.http_delete function to the API documentation
Add any other context or screenshots.
> Updated API docs, removed dated comments

- sql/pg_net.sql
Bug fix
Timed out responses are labeled as successful. 
Please link any relevant issues here: [issue 74](https://github.com/supabase/pg_net/issues/74)
Time out responses are now recognized as "ERRORS"
The unexpected test failures in my recent pull requests ([1](https://github.com/supabase/pg_net/actions/runs/4987953205/attempts/5), [2](https://github.com/supabase/pg_net/pull/91)), which only modified documentation, prompted me to investigate the error. The root cause appears to be timeouts during test endpoint calls to https://httpbin.org. If the response exceeds the default 2-second timeout, `net._http_collect_response` returns a misleading success status:
```markdown
| status  | message | response |
| ------- | ------- | -------- |
| SUCCESS | ok      | (,,)     |
```
When the tests …
> Updated SQL: Timed out responses are no longer recorded as "SUCCESSFUL"

- nix/nginx/conf/custom.conf
- shell.nix
- test/test_http_delete.py
- test/test_http_headers.py
- test/test_http_params.py
- test/test_http_post_collect.py
- test/test_http_requests_deleted_after_ttl.py
Move all the tests from httpbin.org to local openresty server
Following up from https://github.com/supabase/pg_net/pull/99#issuecomment-1669975876
> test: httpbin.org -> localhost:8080

- Makefile
- pg_net.control.in
This way we define the version on a single place (Makefile EXTVERSION).
Related https://github.com/supabase/pg_net/pull/103
> refactor: get version from Makefile for .control

- nix/nginxScript.nix
- nix/pathodScript.nix
- nix/pgScript.nix
- nix/pgValgrindScript.nix
- test/conftest.py
- test/test_engine.py
- test/test_http_delete.py
- test/test_http_errors.py
- test/test_http_get_collect.py
- test/test_http_headers.py
- test/test_http_params.py
- test/test_http_post_collect.py
- test/test_http_requests_deleted_after_ttl.py
- test/test_http_timeout.py
- test/test_worker_error.py
All sqlalchemy `sess.execute` must be used with `text()` otherwise it will fail with:
```
sqlalchemy.exc.ArgumentError: Textual SQL expression
```
Also make all bash scripts fail fast.
Clears item 1 of https://github.com/supabase/pg_net/issues/106.
> chore: compatibility with new python3 packages

- .github/workflows/main.yml
- shell.nix
- src/worker.c
According to https://www.postgresql.org/docs/current/release-16.html.
"Functions that need to be called from the core backend or other extensions must now be explicitly marked PGDLLEXPORT."
> feat: PostgreSQL 16 compatibility

- sql/pg_net.sql
- test/test_worker_error.py
- [fix: check_worker_is_up](https://github.com/supabase/pg_net/commit/b6f6517a0d45ce98de2e610049a5da1f787aeda2)
* Test it works, previously it only tested failure.
> fix: check_worker_is_up

- README.md
Docs Update
The documentation does not reference all the config variables.
Please link any relevant issues here: 
Solves the _primary_ complaint of of ISSUE #97 
The documentation outlines the configuration variables and how to update them.
> Added Configuration variables list to documentation

- README.md
The `net._http_collect_response` was never meant to be used by end users. It only was meant as an internal function for testing.
Why? Because it uses an endless loop (`net._await_response`) which is not safe when running inside a transaction.
Previously it was removed from
https://supabase.com/docs/guides/database/extensions/pg_net
For the same reason.
If there's a need for sync requests, the current recommendation is to use pgsql-http.
---
cc @TheOtherBrian1
> docs: remove net._http_collect_response usage

- Makefile
- README.md
- nix/nginxScript.nix
- nix/pgScript.nix
- sql/pg_net.sql
- src/worker.c
- test/test_http_requests_deleted_after_ttl.py
- test/test_worker_error.py
Otherwise changing a pg_net config requires a restart of the whole database cluster.
Now users can do:
```sql
alter system set pg_net.ttl to '1 hour';
alter system set pg_net.batch_size to 500;
select net.worker_restart();
```
> feat: allow reconfiguring pg_net w/o a db restart

- src/worker.c
- test/test_http_get_collect.py
- test/test_worker_version.py
Closes https://github.com/supabase/pg_net/issues/121
Now the version shows like:
```sql
select backend_type from pg_stat_activity where backend_type like '%pg_net%';
backend_type                                          
-----------------------------------------------------------------------------------------------
pg_net 0.7.3 worker using libcurl/7.73.0 OpenSSL/1.1.1h zlib/1.3 libssh2/1.9.0 nghttp2/1.41.0
(1 row)
```
> feat: show libcurl version

- nix/nginx/conf/nginx.conf
- test/test_http_get_collect.py
Includes an ipv6 only nginx host:
```nginx
server {
listen [::]:8888 ipv6only=on;
location / {
echo 'Hello ipv6 only';
}
}
```
And tests it with pg_net.
> test: resolves ipv6 only host

- src/worker.c
Replace deprecated libcurl symbols
pg_net is using `CURLOPT_PROTOCOLS` which was deprecated in libcurl 7.85.0, causing build error:
src/worker.c: In function 'init':
src/worker.c:153:9: error: 'CURLOPT_PROTOCOLS' is deprecated: since 7.85.0. Use CURLOPT_PROTOCOLS_STR [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Werror=deprecated-declarations8;;]
153 |         curl_easy_setopt(eh, CURLOPT_PROTOCOLS, CURLPROTO_HTTP | CURLPROTO_HTTPS);
|         ^~~~~~~~~~~~~~~~
In file included from src/worker.c:30:
/nix/store/3k4czsnh3wg9liji56v4kjdz3p1mxhsj-curl-8.6.0-dev/include/curl/curl.h:1745:3: note: declared here
1745 |   CURLOPTDEPRECATED(CURLOPT_PROTOCOLS, CURLOPTTYPE_LONG, 181,
|   ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
pg_net …
> feat: use CURLOPT_PROTOCOLS_STR with libcurl >= 7.85.0

- src/worker.c
We should be using `long` instead of `int`:
https://curl.se/libcurl/c/CURLINFO_RESPONSE_CODE.html
Error message when compiling:
```
src/worker.c: In function ‘worker_main’:
src/worker.c:355:57: error: call to ‘_curl_easy_getinfo_err_long’ declared with attribute warning: curl_easy_getinfo expects a pointer to long for this info [-Werror=attribute-warning]
355 |                                                         curl_easy_getinfo(eh, CURLINFO_RESPONSE_CODE, &http_status_code);
|                                                         ^
```
> fix: CURLINFO_RESPONSE_CODE datatype

- src/util.c
- src/worker.c
Failures for curl_easy_setopt and curl_easy_getinfo were not handled.
Also handle NULL Datums.
Fixes #132.
> fix: handle CURL and datum failures

- src/util.h
- src/worker.c
This way the logic is easier to understand, essentially:
```
delete_expired_responses(guc_ttl);
consume_request_queue(curl_mhandle);
insert_curl_responses(curl_mhandle);
```
Also cleanups tabs and instead uses two spaces for indentation.
> refactor: background worker logic into functions

- README.md
- nix/nginx/conf/custom.conf
- nix/nginxScript.nix
- nix/ngx_pathological.nix
- src/util.c
- src/util.h
- src/worker.c
- test/test_http_malformed_headers.py
When having a malformed header such as:
```
$ curl localhost:8080/pathological?malformed-header=header-injection -i
HTTP/1.1 200 OK
Server: nginx/1.26.0
HeaderInjection
Injected-Header: This header contains an injection
```
The background worker crashes.
To prove the above, we use https://github.com/steve-chavez/ngx_pathological.
> Fix malformed headers

- src/worker.c
feature
Changing `pg_net.ttl` and `pg_net.batch_size` requires `ALTER SYSTEM` (which is SU-only) and a config reload.
`pg_net.ttl` and `pg_net.batch_size` can be changed with `ALTER ROLE ... SET ...` + a config reload.
> feat: make ttl & batch_size SUSET

- Makefile
- src/worker.c
Closes https://github.com/supabase/pg_net/issues/143
> fix: show clear error message on older libcurl

- docs/contributing.md
- nix/nginx/conf/custom.conf
- nix/nginx/conf/nginx.conf
- nix/nixops.nix
- nix/nixopsScripts.nix
- nix/pgScript.nix
- shell.nix
- src/worker.c
This is a test that can only be ran manually since it requires AWS. It adds NixOps wrapper scripts to reproduce https://github.com/supabase/pg_net/issues/86.
The steps are:
```
$ net-cloud-deploy
$ net-cloud-reproduce-timeouts
NOTICE:  Waiting until 10000 requests complete
NOTICE:  Stats: {"request_successes":8882,"request_failures":1118,"last_failure_error":"Timeout was reached"}
NOTICE:  Time taken: 00:01:44.341157
```
Then destroy the cloud setup with `net-cloud-destroy`
Note that it takes 01:44, it should be ~50 seconds to finish processing all the 10K requests, considering batch_size=200 (the default).
> test: add cloud test for reproducing timeouts

- Makefile
- src/core.c
- src/core.h
- src/util.c
- src/util.h
- src/worker.c
This replaces the usage of [curl_multi_perform](https://curl.se/libcurl/c/curl_multi_perform.html) (which uses `select()`) for [curl_multi_socket_action](https://curl.se/libcurl/c/curl_multi_socket_action.html) + `epoll()`, which is more performant (requests finish in less time) and more reliable (with 0 timeouts). 
It solves #86. Using the cloud test added on https://github.com/supabase/pg_net/pull/150, on this branch we get the following results:
```
postgres=# call repro_timeouts(10000);
NOTICE:  Waiting until 10000 requests complete
NOTICE:  Stats: {"request_successes":10000,"request_failures":0,"last_failure_error":null}
NOTICE:  Time taken: 00:01:01.360567
CALL
postgres=# call repro_timeouts(20000);
NOTICE:  Waiting until 20000 requests complete
NOTICE:  Stats: …
```
> feat: epoll based worker

- README.md
- sql/pg_net--0.11.0--0.11.1.sql
- sql/pg_net.sql
- src/worker.c
- test/test_privileges.py
- test/test_worker_error.py
Closes https://github.com/supabase/pg_net/issues/72. Also addresses https://github.com/orgs/supabase/discussions/21450.
> fix: permission denied for new roles and remove security definer functions

- nix/pgScript.nix
- test/test_privileges.py
Ensures pre-existing roles are able to use the net schema.
> test: privilege of pre-existing role

- .github/workflows/main.yml
- Makefile
- nix/pg_net.nix
- nix/postgresql/generic.nix
- shell.nix
- sql/pg_net--0.12.0--0.13.0.sql
- src/core.c
- src/core.h
- src/event.c
- src/event.h
- src/worker.c
- test/test_http_timeout.py
Also adds MacOS CI and makes Nix env macos compatible.
> feat: use kevent for macos compatibility

- src/event.c
- src/worker.c
- test/test_user_db.py
This is so `select * from pg_stat_activity where application_name like '%pg_net%';` can work as usual.
> feat: set appname for pg_stat_activity entry

- Makefile
- src/core.c
- src/errors.c
- src/errors.h
- src/event.h
- src/util.c
- src/util.h
- src/worker.c
- test/test_http_timeout.py
Closes https://github.com/supabase/pg_net/issues/169.
When a timeout occurs, now the error message is like:
```
Timeout of 1000 ms reached. Total time: 1000.527000 ms (DNS time: 0.084000 ms, TCP/SSL handshake time: 0.314000 ms, HTTP Request/Response time: 1000.014000 ms)
```
Before it used to be:
```
Timeout was reached
```
> feat: add detailed timeout error

- nix/nginx/conf/custom.conf
- sql/pg_net--0.14.0--0.15.0.sql
- sql/pg_net.sql
- src/core.c
- test/test_http_delete.py
Addresses https://github.com/supabase/pg_net/issues/77#issuecomment-1465029556. Now it's possible to do:
```sql
select net.http_delete(
url  :='http://localhost:8080/delete_w_body'
,   body := '{"key": "val"}'
);
```
Backwards compatibility is tested. No body will be sent if the body parameter is NULL (the default).
- I tried adding an overloaded function for `net.http_delete` instead of modifying the existing one, but that caused breakage since every call like:
```sql
select net.http_delete(
url:='http://localhost:8080/delete'
,   params:= '{"param-foo": "bar"}'
,   headers:= '{"X-Baz": "foo"}'
);
```
Failed with an error related to ambiguity (two functions with the same named parameters).
> feat: support net.http_delete with request body

- .gitignore
- sql/pg_net--0.15.0--new.sql
- sql/pg_net.sql
- src/util.c
- test/test_http_errors.py
Closes https://github.com/supabase/pg_net/issues/172.
A test is added on a previous commit to ensure the behavior is maintained.
Also, remove PARALLEL SAFE since these functions are really PARALLEL UNSAFE, as mentioned on the docs:
> Functions and aggregates must be marked PARALLEL UNSAFE if they write to the database
> https://www.postgresql.org/docs/current/parallel-safety.html
> refactor: remove strict and parallel safe attrs

- .github/workflows/main.yml
- .gitignore
- nix/loadtest.nix
- nix/nixops.nix
- nix/xpg.nix
- shell.nix
- test/init.sql
- test/loadtest/loadtest.sql
Ensures performance is maintained.
We run `call wait_for_many_gets()` (runs 10K GET requests) in a Nix wrapper script, `net-loadtest`, which measures the CPU and memory each second using `psrecord`. `net-loadtest` can be used locally too.
The result can be visualized on the github action summary, see https://github.com/supabase/pg_net/actions/runs/15548998720?pr=190 (to get here on the UI click the loadtest CI action check below and then click `Summary`). Inline it is:
|   Elapsed time |   CPU (%) |   Real (MB) |   Virtual (MB) |
|----------------|-----------|-------------|----------------|
|          0     |         0 |      20.664 |        218.285 |
|          1     |         1 |      20.789 |        218.691 |
|          2.001 |         3 |      20.914 |        218.691 |
| …
> test: loadtest tracking memory/cpu usage

- .gitignore
- Makefile
- sql/pg_net--0.16.0--0.17.0.sql
- sql/pg_net.sql
- src/pg_prelude.h
- src/worker.c
- test/test_http_requests_deleted_after_ttl.py
- test/test_privileges.py
- test/test_user_db.py
- test/test_worker_behavior.py
Required for solving https://github.com/supabase/pg_net/issues/164, otherwise tests would break.
Adds a `net.wait_until_running` SQL function that waits until the worker runs again after a `net.worker_restart`. This avoids having to do sleeps in tests to wait for the worker to be running again.
For this, we add some states for the background worker state machine. This to allow waiting until it reaches a RUNNING state on tests.
> feat: add `net.wait_until_running` sql function 

- README.md
- src/worker.c
PGC_SUSET was used for `pg_net.ttl/batch_size`, which was incorrect because those cannot be altered via `SET`, since the background worker runs outside of the client session.
Now an adequate PGC_SIGHUP is used for them.
PGC_SIGHUP was used for `pg_net.username/database_name`, which was incorrect since those can't be reloaded unless the worker restarts (BackgroundWorkerInitializeConnection can only be done at startup).
Now an adequate PGC_SU_BACKEND is used for them.
Also change the README.md to clarify the former require `pg_reload_conf` while the latter require a `net.worker_restart`.
> fix: incorrect GUC contexts

- test/test_privileges.py
This shows on pytest:
WARNING:  SET LOCAL can only be used in transaction blocks
Fix that by removing an unnecessary set local postgres. Plus ensure the tests are executed with the roles set with `set local role X`.
> test: fix set local warnings

- Makefile
- sql/pg_net--0.19.1--0.19.2.sql
- src/core.c
- src/worker.c
- test/test_http_requests_deleted_after_ttl.py
- test/test_worker_behavior.py
If the worker process the queue for a long time, it will preventing operations like TRUNCATE or VACUUM FULL from completing.
This is because it acquires an AccessShareLock on the extension tables and only releases it once it goes to sleep.
Now we use `ConditionalLockRelationOid` and unlock the tables at the end of each transaction, allowing VACUUM FULL or TRUNCATE to finish fast.
> fix: locking the tables for too much time

- Makefile
- sql/pg_net--0.19.4--0.19.5.sql
- src/pg_prelude.h
- src/worker.c
Before the shared memory wasn't guarded with lwlocks plus there was no call to RequestAddinShmemSpace to estimate used memory (the latter only available on pg >= 15).
Closes https://github.com/supabase/pg_net/issues/220
> fix: incorrect shared memory setup 

- .github/workflows/main.yml
- .gitignore
- nix/loadtest.nix
- nix/xpg.nix
- test/utils/loadtest.sql
Checks performance and CPU/MEM usage of different batch_size and number of requests.
The results show on CI, and can be shown the same locally too.
See https://github.com/supabase/pg_net/actions/runs/17218819358?pr=230
> test: loadtest with varying reqs and batch_size
