supabase/pg_net

.gitignore, curl_worker.control, shell.nix, sql/curl_worker--0.1.sql, src/worker.c, test/expected/test__install.out, test/expected/test_http_cancel_request.out, test/expected/test_http_collect_response.out, test/expected/test_http_get.out, test/fixtures.sql, test/sql/test__install.sql, test/sql/test_http_cancel_request.sql, test/sql/test_http_collect_response.sql, test/sql/test_http_get.sql
* inserts response body as text into response table
* inserts headers as jsonb in the response table
* inserts ContentType and timedOut in response table
* removes the uuid-ossp dependency(back to bigint)
=> Insert values into response table from the background worker

.github/workflows/main.yml, .gitignore, shell.nix, src/worker.c, test/conftest.py, test/test_engine.py, test/test_http_get_collect.py
Use python/pytest for isolation tests since pg_isolation_regress isn't available and multiple transactions are needed
=> Isolation tests

src/worker.c, test/test_http_params.py, test/test_http_requests_deleted_after_ttl.py
Fixes #24.
Also added a safeguard against doing requests against other valid protocols(like ftp, smtp, etc).
=> Restart worker

docs/api.md, sql/pg_net--0.1.sql, test/test_http_post_collect.py, test/test_http_requests_deleted_after_ttl.py
=> http_post json only

README.md, docs/api.md, docs/contributing.md, docs/index.md, docs/installation.md
Update the docs
Changes visible at https://supabase.github.io/pg_net
=> sync docs with sql

docs/api.md, sql/pg_net--0.1.sql
=> fix: remove timeout_milliseconds option

.github/workflows/main.yml, Makefile, nix/format.nix, nix/pgScript.nix, shell.nix, src/util.c, src/util.h, src/worker.c
=> Enforce clang-format on CI

sql/pg_net.sql
Previously updated in pg_net--0.3--0.4.sql, but forgot to update here.
=> fix: add security definer opt in pg_net.sql

.github/workflows/main.yml, Makefile, nix/deploy.nix, nix/nginx/conf/custom.conf, nix/nginx/conf/nginx.conf, nix/nginx/conf/slow-reply.conf, nix/nginxScript.nix, nix/pathodScript.nix, nix/pgScript.nix, pg_net.control, shell.nix, sql/pg_net--0.5.1--0.6.sql, sql/pg_net.sql, src/worker.c, test/fixtures.sql, test/test_http_errors.py, test/test_http_post_collect.py, test/test_http_requests_deleted_after_ttl.py, test/test_http_timeout.py
Immediate benefit is that it fixes https://github.com/supabase/pg_net/issues/66, added a test for proving it.
Also planning to add [mitmproxy's pathod](https://2qwesgdhjuiytyrjhtgdbf.readthedocs.io/en/latest/pathod/intro.html#pathod) for testing against other http faillures like disconnects. 
Will refine other things along the way.
=> revert to non-libuv worker, fix all pending bugs

pg_net.control, sql/pg_net--0.7--0.7.1.sql, sql/pg_net.sql, src/worker.c
Fixes https://github.com/supabase/pg_net/issues/82
=> fix: restore the net.http_collect_response 

.github/workflows/release.yml
https://github.com/supabase/pg_net/actions/runs/4321158504/jobs/7542101601
=> chore(ci): fix .deb release action

README.md
The documentation is dated. Some sections have not been updated in over two years. Recognizing the importance of robust and current documentation, I expanded the Readme to be comprehensive, covering all aspects of the project, including newly introduced features, such as the net.http_delete function, practical examples to guide users, and clear instructions for installation.
Prior to this update, the Readme document provided minimal guidance. It lacked a reference to important functions such as net.http_delete and did not offer users practical examples or technical explanations.
The revised Readme now serves as a comprehensive guide to the PG_NET extension. It includes an overview of the project, a detailed table of contents for quick navigation, and a variety of examples demonstrating …
=> Updated Readme to reflect current features

Makefile, src/worker.c
Otherwise is easy to forget updating it.
=> refactor: get EXTVERSION from Makefile on worker

.gitignore, Makefile, nix/nginx/conf/custom.conf, src/worker.c, test/test_http_get_collect.py
Enables https://curl.se/libcurl/c/CURLOPT_FOLLOWLOCATION.html
Closes https://github.com/supabase/pg_net/issues/87
=> fix: pg_net doesn't support redirects

src/worker.c
Better for locality of behavior and reduces LOC
=> refactor: use inline array initialization

sql/pg_net.sql, test/test_http_timeout.py
Partly addresses #86. See https://github.com/supabase/pg_net/issues/86#issuecomment-1898428584
=> fix: increase default timeout

.gitignore, docs/contributing.md, nix/gdbScript.nix, nix/pgScript.nix, nix/pg_net.nix, shell.nix
* Add nix wrapper for GDB.
* Use `log_min_messages=INFO` by default for better debugging.
* Add tags to gitignore.
=> chore: debugging with gdb

.gitignore, docs/contributing.md, nix/bench.sql, nix/gdbScript.nix, nix/nixops.nix, nix/pgScript.nix, shell.nix
=> Some Nix chores

nix/bench.sql, nix/nginx/conf/custom.conf, nix/nginx/conf/nginx.conf, nix/nixops.nix, nix/nixopsScripts.nix
- add utilities for measuring resource usage
- use root nginx location for nixops
=> chore: add nixops ssh wrapper scripts

.github/workflows/main.yml, nix/postgresql/17.nix, nix/postgresql/default.nix, nix/postgresql/generic.nix, nix/postgresql/patches/less-is-more.patch, nix/postgresql/patches/locale-binary-path.patch, nix/postgresql/patches/paths-for-split-outputs.patch, nix/postgresql/patches/paths-with-postgresql-suffix.patch, nix/postgresql/patches/relative-to-symlinks-16+.patch, nix/postgresql/patches/relative-to-symlinks.patch, nix/postgresql/patches/socketdir-in-run-13+.patch, nix/postgresql/patches/socketdir-in-run.patch, nix/postgresql/patches/specify_pkglibdir_at_runtime.patch, shell.nix
=> test: pg 17 compatibility

.github/workflows/main.yml, Makefile, docs/contributing.md, nix/nxpg.nix, nix/postgresql/12.nix, nix/postgresql/13.nix, nix/postgresql/14.nix, nix/postgresql/15.nix, nix/postgresql/16.nix, nix/postgresql/default.nix, nix/postgresql/generic.nix, src/core.c, src/curl_prelude.h, src/errors.c, src/event.c, src/pg_prelude.h, src/util.c, src/worker.c
Trying now to check if coveralls works.
=> chore: compile with Wextra

Makefile
Has the delete with request body feature, see d3125253f084ac605615afbdc69211570d1cd197
=> bump to 0.15.0

src/worker.c
`got_sigterm` is no longer required since `WorkerState.should_restart` is present.
=> refactor: remove got_sigterm variable

src/core.c, src/core.h, src/event.c, src/event.h, src/worker.c, test/conftest.py, test/test_stat_statements.py, test/test_worker_behavior.py
Closes https://github.com/supabase/pg_net/issues/200
=> fix: don't crash when dropping extension

Makefile, test/test_http_requests_deleted_after_ttl.py
Also ensure pytest traces are printed.
=> test: correct TODO in ttl test

test/conftest.py
Forgot to remove this on https://github.com/supabase/pg_net/pull/209.
=> test: remove autocommit from regular Session

.github/workflows/main.yml, Makefile, shell.nix, src/worker.c, test/test_http_errors.py
Reported on https://github.com/NixOS/nixpkgs/pull/422848#issuecomment-3041258219
See https://github.com/NixOS/nixpkgs/pull/422848/commits/101c6df67b2dd214f797585fab07a83749ded36c
=> fix: -Wmissing-variable-declarations compat

test/test_worker_behavior.py
Related to discussion on https://github.com/supabase/postgres/pull/1728#issuecomment-3141266430
=> test: prove drop database with force works ok

Makefile, pg_net.control.in, sql/pg_net--0.19.6--0.19.7.sql, sql/pg_net.sql
Use `module_pathname` to fix this.
=> fix: hardcoding the shared lib name  
